### PR TITLE
[JBEAP-23777] Allow to define one-off patch with name and version separated from base server in patch-config file.

### PR DESCRIPTION
**Pull request by soul2zimate**
Issue: https://issues.redhat.com/browse/JBEAP-23777

please see more information in the issue. thanks.

@kabir please review

### CODE REVIEW

**Comment by kabir** [comment]
@soul2zimate I am not super-familiar, but I think it sounds like you and Brad have got it working? @aloubyansky any concerns?

**Comment by soul2zimate** [comment]
I'd appreciate more eyes on this, I don't want to break anything in patching :) 

I didn't ask Brad to test it as this needs schema change to work.

Basically, this would allow to define a XP one-off patch config like:
`<one-off name="jboss-eap-xp-4.0" applies-to-version="4.0.0.GA" override-identity="true"/>`

Then, go ahead call `patch-gen to` create XP one-off patch zip file with patch.xml content like:

```
<?xml version="1.0" ?>

<patch xmlns="urn:jboss:patch:1.2" id="eapxp-400-745-jbeap-1234">
    <description>
        test
    </description>
    <no-upgrade name="jboss-eap-xp-4.0" version="4.0.0.GA"/>
```

Once we apply the XP one-off patch.zip file on server, it writes to 'jboss-eap-xp-4.0.conf' rather than 'JBoss EAP.conf'.

**Comment by aloubyansky** [comment]
@soul2zimate I'd suggest you and @bmaxwell confirm this is working the way you want it. It's been 5 years since I touched this project and I may be missing some details.

**Comment by kabir** [comment]
> Basically, we need to build a patch-gen SNAPSHOT including this fix

I guess that is good as a test - but that the intent is for this to be merged and released in a future patch-gen?

**Comment by soul2zimate** [comment]
Yes, we would need to merge and release a new `patch-gen`.

But before that, I'd like Brad confirm changes on `JBEAP-23777-master` branch fix all he wants.

**Comment by kabir** [comment]
@soul2zimate Makes perfect sense - thank you

**Comment by soul2zimate** [comment]
just want to mention that since we write the XP one-off patching information into `jboss-eap-xp-4.0.conf`,  
`--patch-stream="jboss-eap-xp-4.0"` must be provided to display XP one-off patch. For example: 

```
[standalone@localhost:9990 /] patch history --patch-stream="jboss-eap-xp-4.0"
[standalone@localhost:9990 /] patch info "my-eapxp-400-745-jbeap-1234" --patch-stream="jboss-eap-xp-4.0"

or 

[standalone@localhost:9990 /] /core-service=patching/patch-stream=jboss-eap-xp-4.0:show-history
[standalone@localhost:9990 /] /core-service=patching/patch-stream=jboss-eap-xp-4.0:patch-info(patch-id=my-eapxp-400-745-jbeap-1234)
```
Because it by default checks default identity "JBoss EAP"

and we won't see XP one-off patch appear in auto completion candidates for command `patch info` and `patch rollback`,  but we can still rollback with the patch id.

**Comment by bmaxwell** [comment]
@soul2zimate I tested, it looks like it works: 

WFLYPAT0050: JBoss EAP cumulative patch ID is: jboss-eap-7.4.5.CP, one-off patches include: none
WFLYPAT0050: jboss-eap-xp-4.0 cumulative patch ID is: jboss-eap-xp-4.0.0.CP, one-off patches include: eapxp-400-745-jbeap-123456

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
2.1.3.Final containing this change was released https://github.com/jbossas/patch-gen/releases/tag/2.1.3.Final. Thanks everyone!

**Pull request merged**
